language: python
python:
  - '3.6.6'
script:
  - make test
after_success:
  - coveralls
deploy:
  provider: heroku
  app: contact-daniel
  api_key:
    secure: D9YzpW6pU6M1KcBWAVdZ7c5ynu5zT2PGVfRb29HxjfzE9wmmoPaTvjYnUX8CDEKssdZycqtRMSapZ70MrwIUksKJ9GTVSFGCOhnTrfy7D981MC2j3t+qN/WuT+BlqY7J559hVpMzAhVQ0NNNu3tbOHd8nv3Aj6IuPJ66KPIRse1u9MKq9nwpYxwZNZXrSgSbI9mDWVee79KMliUA3nAydmRN+PZFTenvHlRHSr5VE+7Dm6jT05Vo67VQGhic4C1pQj+FrkSclVIqjedU4g6gDXrWd09us7mId/Dx/iQ/F3Z3bZV1GvsGIzYc9En6/0H5gXnHyKZiuOWrgBsvK/nMrzxXSJSRR1hjPv+X2kJ34OWZHzlgeA2xYhXDVuF/ZXLt0gKYpf4vamkcRFUwMWwa0Kj6riO7tP3pFiSv02UJ8zObEMWd/dq5vvPx3ZgcZIqab1wmKKARoFVPhqMeBpref+0MAfwOomzHRN6UlQsDf+yYavZWdZuaAtjboSPaRNQNlzLKqbggJ1+f7dkmCIiWV40sk6MYDNYsUf9cEDOz+mzA4Fmc6gjYYDFjB7xzshBSQrupoZEN3ruG8FWBc4IsQpvAX6QAbyb06peoJfQwsqxtYsyjoOneyKQcCWGSEDcSEQwwldt7S0pxvP49YOWCGy9szhDAED8KJke8QEYrAkE=
