language: python
python:
    - "3.6.5"
script:
    - make test
after_success:
    - coveralls
deploy:
    provider: heroku
    app: contact-daniel
    api_key:
        secure: LUg0/LCAjd4ACBA6KMJ8Ddzjx5P9Lk4tdwQ07fyK2vNEqjFg3YsBNu0MCjPw7DEHRDp+C+D98l3C8hM0sxy0qLBSVff3zR4icFieZStfsr0dgpR0xDbB2HbGlVpZ95bh/3RjS06/cPBfbiiC2tDAyWY4vdfvMvmF5E6OjE1rIPiiUKHYcu7t3i4e3yBWs4Eja2zzU84UAZAjBjHtL4yG/8V7HhVJy9qxfot5pdye9XOzaCsuSuFULXkcpYK5G9VDbO5YRWL1AvBwJ57IzPtfiBEMDst46o28Mr/JT422XWcVb5T0lHYJAN+Jb27jM5DkVvBhasvVfzWpvhTzHvCR1wFeLRiyItK0K+uYjUxvi7uyJ5YLso4IXSlCt9506haHpjVf4nxT3esIecVXlp8D8mK9+nLJgCnYaq0DgHgg/EwbOSgIY3l21wazt7esyKWsubfyOZpdTy+CXKjjrJXrJfrf5AHeZrWcR95cWTbsgIGEokdNRMqDftUJPUvkGFACWfv0CUxbAiMlb5kc42M5SyhV6weVFWNTrwhA5Bdl5GvrcunC0sqxLTDRbDls+kzp9qtXvg1CtF7wYBZQUU3lPyDt2EYnfLzmX8CpNVt+zP+EZnQTuUmWBl6ox9t/E4KDi09dqT7WsyMV/2xFA8pSCMtZ4MjZzWHtgfw5UGVI/DE=
