name: build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Lint
        run: make lint
      - name: Run Tests
        run: |
          make test
          coverage report
